-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Adwaita")
hl.env("XCURSOR_SIZE", "24")

-- Settings
hl.config({
    decoration = {
        active_opacity = 1.0,
        blur = {
            enabled = true,
            ignore_opacity = true,
            passes = 4,
            popups = true,
            size = 2,
            special = true,
            xray = false,
        },
        dim_inactive = false,
        fullscreen_opacity = 1.0,
        inactive_opacity = 1.0,
        rounding = 5,
        rounding_power = 5.0,
        shadow = {
            enabled = true,
        },
    },
    general = {
        allow_tearing = true,
        border_size = 1,
        col = {
            active_border = "0xff1a5fb4",
            inactive_border = "0xff3d3846",
        },
        extend_border_grab_area = 8,
        gaps_in = 4,
        gaps_out = 9,
        hover_icon_on_border = true,
        resize_on_border = true,
        snap = {
            border_overlap = false,
            enabled = true,
            respect_gaps = true,
        },
    },
})

-- Animations
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 1.0,
    bezier = "default",
})

-- Monitors: managed in ~/.config/hypr/monitors.lua (Omarchy side).
-- The stale eDP-1 rule HyprMod saved here (scale 1.5, position 2420x1350)
-- was removed — it fought the catch-all rule in monitors.lua.

-- Workspaces
hl.workspace_rule({
    workspace = "1",
})
